artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/cancer_detection_data
  source_URL: https://github.com/kevoa/Zips/raw/main/df6.zip
  local_data_file: artifacts/cancer_detection_data/data.zip
  unzip_dir: artifacts/cancer_detection_data

data_validation:
  root_dir: "artifacts/data_validation"
  data_file: "artifacts/cancer_detection_data/df6.xlsx"
  status_file: "artifacts/data_validation/status.txt"
  sequences_to_remove: ["*", "**"]
  target_column: "Tumor type"
  columns_to_remove: 
    - "Unnamed: 0"
    - "Patient ID #"
    - "Sample ID #"
    - "CancerSEEK Test Result"
    - "CancerSEEK Logistic Regression Score"
  validated_data_file: "artifacts/data_validation/validated_data.xlsx"


data_transformation:
  root_dir: "artifacts/data_transformation"
  validated_data_file: "artifacts/data_validation/validated_data.xlsx"
  transformed_train_data_path: "artifacts/data_transformation/train_df.xlsx"
  transformed_test_data_path: "artifacts/data_transformation/test_df.xlsx"
  target_column: "Tumor type"
  ordinal_features: ["AJCC Stage"]
  nominal_features: ["Sex"]


model_trainer:
  root_dir: "artifacts/model_trainer"
  train_data_path: "artifacts/data_transformation/train_df.xlsx"
  test_data_path: "artifacts/data_transformation/test_df.xlsx"
  model_name: "model.joblib"
  important_features: 
    - 'sFas (pg/ml)'
    - 'sHER2/sEGFR2/sErbB2 (pg/ml)'
    - 'CA 15-3 (U/ml)'
    - 'CA19-9 (U/ml)'
    - 'CA-125 (U/ml)'
    - 'TIMP-2 (pg/ml)'
    - 'TGFa (pg/ml)'
    - 'Sex_1'
    - 'Leptin (pg/ml)'
    - 'IL-8 (pg/ml)'
    - 'IL-6 (pg/ml)'
    - 'AFP (pg/ml)'
    - 'GDF15 (ng/ml)'
    - 'Prolactin (pg/ml)'
    - 'HGF (pg/ml)'
    - 'CD44 (ng/ml)'
    - 'Midkine (pg/ml)'
    - 'Thrombospondin-2 (pg/ml)'
    - 'TIMP-1 (pg/ml)'
    - 'HE4 (pg/ml)'
  target_column: "Tumor type"
